<?php


namespace Weaver;


use Danack\Code\Generator\ClassGenerator;
use Danack\Code\Reflection\ClassReflection;

/**
 * @param $savePath
 * @param $fqcn
 * @param $text
 * @throws WeaveException
 */
function saveFile($savePath, $fqcn, $text) {

    $filename = str_replace('\\', '/', $fqcn);

    $fileHeader = <<< END
<?php

//Auto-generated by Weaver - https://github.com/Danack/Weaver
//
//Do not be surprised if any changes to this file are over-written.
//

END;

    $outputFilename = $savePath.'/'.$filename.'.php';
    @mkdir(dirname($outputFilename), 0777, true);
    $written = @file_put_contents($outputFilename, $fileHeader.$text);

    if ($written == false) {
        throw new WeaveException(
            "Failed to write file $filename.",
            WeaveException::IO_ERROR
        );
    }
}




class WeaveResult {

    /**
     * @var \Danack\Code\Generator\ClassGenerator
     */
    public $generator;

    /**
     * @param ClassGenerator $generator
     * @param FactoryGenerator $factoryGenerator
     * @internal param ClassReflection $sourceReflection
     * @internal param ClassReflection $decorationReflection
     */
    function __construct(ClassGenerator $generator, FactoryGenerator $factoryGenerator = null) {
        $this->generator = $generator;
        $this->factoryGenerator = $factoryGenerator;
    }

    /**
     * @param $fqcn
     */
    public function setFQCN($fqcn) {
        $this->generator->setFQCN($fqcn);
    }

    /**
     * @param $outputDir
     * @param null $outputClassname
     * @return string
     * @throws WeaveException
     */
    public function writeFile($outputDir, $outputClassname = null) {
        if ($outputClassname) {
            $this->setFQCN($outputClassname);
        }

        saveFile($outputDir, $this->generator->getFQCN(), $this->generator->generate());

        return $this->generator->getFQCN();
    }

    /**
     * @param $outputDir
     * @param null $factoryClassname
     * @return null|string
     * @throws WeaveException
     */
    public function writeFactory($outputDir, $factoryClassname = null) {
        if (!$factoryClassname) {
            $factoryClassname = $this->generator->getFQCN().'Factory';
        }

        $generator = $this->generateFactory($factoryClassname);
        saveFile($outputDir, $factoryClassname, $generator->generate());
        
        return $factoryClassname;
    }

    /**
     * @param $factoryClassname
     * @return ClassGenerator
     */
    public function generateFactory($factoryClassname) {
        $generator = $this->factoryGenerator->generateClassFactory($factoryClassname, $this->generator->getFQCN());

        return $generator; 
    }
    
    public function generateClosureFactoryFunction($factoryClass) {
        return $this->factoryGenerator->generateClosureFactoryFunction($factoryClass, $this->generator->getFQCN());
    }
}

 