<?php


namespace Weaver;

use Zend\Code\Generator\ParameterGenerator;

/**
 * @param ParameterGenerator[] $constructorParameters
 * @param bool $includeTypeHints
 * @return string
 */
function getConstructorParamsString($constructorParameters, $includeTypeHints = false) {
    $string = '';
    $separator = '';

    foreach ($constructorParameters as $constructorParameter) {
        $string .= $separator;

        /** @var $constructorParameter ParameterGenerator */
        if ($includeTypeHints) {
            $typeHint = $constructorParameter->getType();
            if ($typeHint) {
                $string .= $typeHint.' ';
            }
        }

        $string .= '$'.$constructorParameter->getName();
        $separator = ', ';
    }

    return $string;
}


/**
 * @param $savePath
 * @throws \RuntimeException
 */
function saveFile($savePath, $fqcn, $text) {

    @mkdir($savePath, true);
    $filename = str_replace('\\', '/', $fqcn);

    $fileHeader = <<< END
<?php

//Auto-generated by Weaver - https://github.com/Danack/Weaver
//
//Do not be surprised if any changes to this file are over-written.

END;

    $written = file_put_contents($savePath.'/'.$filename.'.php', $fileHeader.$text);

    if ($written == false) {
        throw new \RuntimeException("Failed to write file $filename.");
    }
}



interface WeaveGenerator {
    function writeClass($directory);
    function writeFactory($directory);
}

 